### ISSUE TITLE
Add Unit Test for ctil::ends_with in test.cpp

### ISSUE THREAD

**Issue by rjwignar** [rjwignar/ctil#13]
`ctil::ends_with()` is a helper method that checks if a string, `value`, ends with a suffix, `ending`.
This method is used to check if **file paths** passed to `ctil` contains specific file extensions.
A unit test has to be added to `test.cpp` that tests `ctil::ends_with()`.

To do this:
- Clone the repository's **master branch**.
- Open `ctil.sln` in Visual Studio (2019 or 2022).
- Add your test to `test.cpp`.
- Unit tests are written in [Google Tests](https://github.com/google/googletest).
  - A primer on Google Test is available [here](https://google.github.io/googletest/primer.html).
 - You can refer to the primer or refer to other tests written in `test.cpp` for examples.

**Comment by kliu57** [comment]
I can work on this :)
