### ISSUE TITLE
Fix file name retrieval

### ISSUE THREAD

**Issue by pbelokon** [rjwignar/ctil#2]
## Description

The way newName is created does not allows user to pass any file with a "." for example if I  have a file ``new.story.txt`` the html file would be called ``new.html``. try using `` find(".txt")) ``

## Issue code
```cpp

 newName = ((std::string)argv[1]).substr(0, ((std::string)argv[1]).find(".")) + ".html";

```

**Comment by rjwignar** [comment]
I have updated `newName`'s initialization with your suggestion. Please see commit `d8afc36` here:  https://github.com/rjwignar/ctil/commit/d8afc36d9fcb2f20f459ba2a88a4d003aa0c54e7
